------------------------------
-- dropping existing tables --
------------------------------

drop table PAYMENT;
drop table CART;
drop table ORDERS;
drop table MENU_ITEMS;
drop table USERS;

-------------------------
-- creating the tables --
-------------------------

CREATE TABLE USERS
(
   USER_ID VARCHAR (10) ,
   USER_NAME VARCHAR (50) NOT NULL UNIQUE,
   USER_ADDRESS VARCHAR(100) NOT NULL,
   USER_PWD VARCHAR (20) NOT NULL UNIQUE,
   USER_TYPE CHAR(10) NOT NULL,
   USER_EMAIL VARCHAR(50) NOT NULL,
  PRIMARY KEY(USER_ID)
);
CREATE TABLE MENU_ITEMS
(
    ITEM_ID VARCHAR (10) ,
   ITEM_NAME CHAR (50) NOT NULL UNIQUE,
   ITEM_PRICE DECIMAL(10, 2) NOT NULL,
   ITEM_URL VARCHAR (100),
   
  PRIMARY KEY(ITEM_ID)
);
CREATE TABLE ORDERS
(
    ORDER_ID VARCHAR (10) ,
   USER_ID VARCHAR (10),
   ORDER_TYPE CHAR(10),
   ORDER_STATUS CHAR (10) DEFAULT 'PREPARING',
   ORDER_DATETIME DATETIME, 
  PRIMARY KEY(ORDER_ID),
  FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
);
CREATE TABLE CART
(
    CART_ID VARCHAR (10) ,
   ORDER_ID VARCHAR (10),
   ITEM_ID VARCHAR(10),
  QUANTITY INT (2),
   TOTAL_PRICE DECIMAL(10, 2), 
  PRIMARY KEY(CART_ID),
  FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID),
  FOREIGN KEY (ITEM_ID) REFERENCES MENU_ITEMS (ITEM_ID)
);
CREATE TABLE PAYMENT
(
    PAYMENT_ID VARCHAR (10) ,
   ORDER_ID VARCHAR (10),
   PAYMENT_STATUS CHAR(10) DEFAULT 'UNPAID',
  PAYMENT_AMOUNT DECIMAL(10, 2),
  PRIMARY KEY(PAYMENT_ID),
  FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID)
  
);
